### ISSUE TITLE
Plugin features fail if folder container DBContexts is not directly under thew workspace

### ISSUE THREAD

**Issue by erikrenaud** [badsyntax/vscode-entity-framework#100]
At the root of my project, i have a "src" folder and then the "models" folder that contains the EFCore DBContexts.

Extension fails as the "dotnet ef ...." commands are executed at the workspace root, without taking the full path into consideration.
i.e.
"models" instead of "src/models".

Workaround, re-open VS Code on the SRC folder.

**Comment by badsyntax** [comment]
Thanks for the bug report. Can you paste the full ef command the extension is executing when you open the project from the root?

**Comment by erikrenaud** [comment]
> port. Can you paste the full ef command the extension is executing when you open the project from the root?

Of course - should had done that in my initial message..

11:37:25 [info] dotnet ef dbcontext list --project "Models" --startup-project "Models"
11:37:26 [error] Unable to get dbContexts: Unable to retrieve project metadata. Ensure it's an SDK-style project. If you're using a custom BaseIntermediateOutputPath or MSBuildProjectExtensionsPath values, Use the --msbuildprojectextensionspath option.

My folder hierarchy is:
c:/src/PROJECT/src/Models
The folder that is opened in VSCODE is c:/src/PROJECT
Everything work if i open VSCODE in c:/src/PROJECT/src

**Comment by Kombuchelada** [comment]
@erikrenaud I was running into a similar issue and I was able to fix it with a workaround. If you go to your `settings.json` file you will find an entry for "entityframework.commands". I was able to modify the arguments for each command to work with my folder structure there.

**Comment by iPlexor** [comment]
@Kombuchelada This worked for me, but a bit fiddly and not ideal to modify the main `settings.json` so here's what I did.

1. Added .vscode/settings.json to my root folder (the one I'm opening in VSCode), obviously if you have one just edit that.

2. In there I pasted a full copy of the entityframework.commands block found in my main settings.json 

3. I then did a find and replace on $project, using my custom path which for me was just src/$project. 

``` JSON
{
  "entityframework.commands": {
    "addMigration": [
      "dotnet",
      "ef",
      "migrations",
      "add",
      "\"$migrationName\"",
      "--project",
      "\"src/$project\"",
      "--startup-project",
      "\"src/$project\"",
      "--context",
      "\"$dbContext\""
    ],
   // other commands
}
```

I hit refresh in the EF Extension and it found it. Bizarrely, the extension always found my EF project, but failed to load any contexts. 

I wish the EF Core tools were not so full of janky gotchas like this.

Great extension @badsyntax!

**Comment by badsyntax** [comment]
Hi. I've added some updates to the extensions which should hopefully help with this.

Instead of modifying the commands config, you can now set `entityframework.project` & `entityframework.startupProject` in the config.

To make this easier for users, you can set these by clicking on the "Configure" icon in the Entity Framework treeview:

<img width="400" alt="Screenshot 2024-09-22 at 09 14 35" src="https://github.com/user-attachments/assets/5e41bc65-ef7e-4556-8b08-b7dad1c1d86d">

Let me know if you're still having problems!
