### ISSUE TITLE
[Question] Mermaid screenshot

### ISSUE THREAD

**Issue by ErikEJ** [badsyntax/vscode-entity-framework#106]
The image showing the mermaid viewer - where is that from?

**Comment by badsyntax** [comment]
Hi @ErikEJ . The screenshot in the README is generated via the extension. A webview is rendered and a mermaid diagram is rendered based on the DB schema.  A t4 template is used to generate the mermaid diagram: https://github.com/badsyntax/vscode-entity-framework/blob/master/src/templates/DbContext.Mermaid.t4

**Comment by badsyntax** [comment]
I recognise the README can be improved to explain this better. I'll be doing more .NET dev come the new year and will be improving this extension in the coming weeks/months. I'm aware of all your excellent [visual studio extensions](https://marketplace.visualstudio.com/publishers/ErikEJ), let me know if you'd be interested to collaborate in any form.

**Comment by ErikEJ** [comment]
A command to launch EF Core Power Tools CLI would be a great addition!
