### ISSUE TITLE
Set startup project option

### ISSUE THREAD

**Issue by ahmet-cetinkaya** [badsyntax/vscode-entity-framework#107]
I have multiple projects in a solution (SLN). The DbContext and other related components are in the Persistence project, but the application starts in the WebAPI project. However, when running dotnet ef commands, the extension uses the same startup project as specified in the project options. Is it possible to specify a different startup project for these commands?

```
12:54:04 [info] Extension activated
12:54:04 [info] Discovered 1 compatible projects
12:54:16 [info] dotnet ef dbcontext list --project "Persistence" --startup-project "Persistence"
12:54:16 [error] Unable to get dbContexts: Unable to retrieve project metadata. Ensure it's an SDK-style project. If you're using a custom BaseIntermediateOutputPath or MSBuildProjectExtensionsPath values, Use the --msbuildprojectextensionspath option.
```

**Comment by badsyntax** [comment]
I've added a feature to set the `project` and `startupProject` with PR: #109 

Can you try the latest version of the extension and let me know if this improves things for you?
