### ISSUE TITLE
Set project paths

### ISSUE THREAD

**Issue by ahmet-cetinkaya** [badsyntax/vscode-entity-framework#108]
I would like to request the addition of a feature that allows users to select specific paths within the project, such as src/Persistence. This enhancement would facilitate more efficient management and navigation of large projects by providing a list of available paths, enabling selection, and incorporating search and filter options.

```
12:54:04 [info] Extension activated
12:54:04 [info] Discovered 1 compatible projects
12:54:16 [info] dotnet ef dbcontext list --project "Persistence" --startup-project "Persistence"
12:54:16 [error] Unable to get dbContexts: Unable to retrieve project metadata. Ensure it's an SDK-style project. If you're using a custom BaseIntermediateOutputPath or MSBuildProjectExtensionsPath values, Use the --msbuildprojectextensionspath option.
```

`dotnet ef dbcontext list --project "Persistence" --startup-project "Persistence"` -> `dotnet ef dbcontext list --project src/Persistence --startup-project src/WebAPI`

**Comment by badsyntax** [comment]
I've added a feature to set the `project` and `startupProject` with PR: #109 

Can you try the latest version of the extension and let me know if this improves things for you?
